### ISSUE TITLE
Register plugins failed from electrode app server

### ISSUE THREAD

**Issue by ajaxdinesh** [electrode-io/electrode-server#28]
I am new for Electrode. I tried to implement 'electrode-app as per the document. When i run the below command after created electrode-app folder and got an error message as mentioned in the below image. Could you please help me to fix this issue?
$ clap dev
![image](https://user-images.githubusercontent.com/387259/34968252-806fcb40-fa25-11e7-9a3e-9a95e5bb8d1b.png)

**Comment by dsumman** [comment]
Hi there

I too am having the exact same problem - as well as all the developers I work with. We are considering the use of electrode for use in the next gen architecture for front end.  Due to it being an enterprise environment we have to use Windows machines.

Also after the 'ignite generate-app' command, the process failed to install some modules which had to be installed by using 'yarn install' within the project directory. 

Webpack does not seem to be transpiling the jsx files in client and server folders.

Thanks for your help - we would really like to use electrode, but currently this is completely stopping us.

I have attached some screenshots of the problem 
<img width="995" alt="electrode problems" src="https://user-images.githubusercontent.com/29458069/35266171-4c02f0f8-001a-11e8-82e0-6ba71b99d209.png">
<img width="805" alt="windows information" src="https://user-images.githubusercontent.com/29458069/35266173-4c5d4594-001a-11e8-950d-1d6385f98b8b.png">

**Comment by ajaxdinesh** [comment]
Thanks for your information. I installed node version >9.0 and yarn not supported during the installation. So i downgrade the version 8.0.0 and re-generate the electrode app and now working fine.

**Comment by dsumman** [comment]
Thanks Ajaxdinesh

I had tried downgrading but my issue was i didnt go back far enough.

I can confirm that by reducing the node version installed on the machine to 8.0.0 ( I used NVM ) it does indeed work and the import failures have disappeared.

Thanks for pointing me in the right direction regarding this problem, well done in finding that fix.

I am however slightly concerned that I could not find this information was not available in any of the documentation - and if it were, it was not upfront and center.  When choosing to use frameworks like this, if automated generators do not work because of obscure problems it causes a huge dent in confidence of that product (what else could go wrong down the line?)

<img width="800" alt="working hapijs" src="https://user-images.githubusercontent.com/29458069/35324315-4af93612-00e8-11e8-976b-48cffa777ac2.png">
